# Generated by Django 4.2.5 on 2023-09-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cv', '0002_alter_skill_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='user',
            new_name='name',
        ),
    ]
