# Generated by Django 4.2.5 on 2023-09-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cv', '0003_rename_user_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_active',
        ),
    ]
