# Generated by Django 4.2.5 on 2023-09-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cv', '0004_remove_education_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate'),
        ),
    ]
