# Generated by Django 4.2.5 on 2023-09-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cv', '0005_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education'),
        ),
    ]
