# Generated by Django 4.2.5 on 2023-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cv', '0006_education_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='url_credential',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='company',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
