# Generated by Django 4.2.5 on 2023-09-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cv', '0007_remove_certificate_url_credential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
