# Generated by Django 4.2.5 on 2023-09-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_cv', '0008_alter_certificate_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['date'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
